language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t monkeysoft68/docker-react -f Dockerfile.dev .

script:
  - docker run e- CI=true monkeysoft68/docker-react npm run test
  